### ISSUE TITLE
Answers State doesn't always reflect result of most recent action

### ISSUE THREAD

**Issue by bhainesva** [yext/answers-headless-react#31]
Hello, 

I've noticed that the answers state doesn't always reflect the results of the most recently initiated action. Specifically, given two searches, if the first one takes longer to execute than the second its results can override the values in state. 

A practical use case for this is autocomplete, where requests can be fired very rapidly in response to keystrokes. 

Here's an example, the autocomplete suggestions that get rendered here aren't deterministic:

```
function Test() {
  const ur = useAnswersState(s => s.universal.autoComplete?.results)
  const answersActions = useAnswersActions()

  useEffect(() => {
    answersActions.setQuery('')
    answersActions.executeUniversalAutoComplete();
    answersActions.setQuery('iphone')
    answersActions.executeUniversalAutoComplete();
  }, [])

  return (
    <div>
      {ur?.map((r, i) => <div key={i}>{r.value}</div>)}
    </div>
  )
}
```

**Comment by tmeyer2115** [comment]
@bhainesva, we made changes to Headless that guarantee you get the results of the most recent action.
